version: '3'

volumes:
  pg_data1_production:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data1_production:/var/lib/postgresql/data

  backend:
    image: svitsov/kittygram_final_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media

  frontend:
    env_file: .env
    image: svitsov/kittygram_final_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: svitsov/kittygram_final_gateway
    env_file: .env
    volumes:
      - static:/static/
      - media:/media
    ports:
      - 9000:80