version: '3'

volumes:
  pg_data1_production:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data1_production:/var/lib/postgresql/data

  backend:
    image: svitsov/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    env_file: .env
    image: svitsov/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: svitsov/kittygram_gateway
    env_file: .env
    volumes:
      - static:/static
      - media:/app/media
    ports:
      - 9000:80
    depends_on:
      - backend
      - frontend